/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.adventofcode.kotlin-application-conventions")
}

dependencies {

}

application {
    // Define the main class for the application.
    mainClass.set("org.aoc.AppKt")
}